/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutAboutIdRouteImport } from './routes/about/$aboutId'

const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAboutIdRoute = AboutAboutIdRouteImport.update({
  id: '/about/$aboutId',
  path: '/about/$aboutId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/about/$aboutId': typeof AboutAboutIdRoute
  '/about': typeof AboutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/about/$aboutId': typeof AboutAboutIdRoute
  '/about': typeof AboutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/about/$aboutId': typeof AboutAboutIdRoute
  '/about/': typeof AboutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/main' | '/about/$aboutId' | '/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/main' | '/about/$aboutId' | '/about'
  id: '__root__' | '/' | '/main' | '/about/$aboutId' | '/about/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRoute
  AboutAboutIdRoute: typeof AboutAboutIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$aboutId': {
      id: '/about/$aboutId'
      path: '/about/$aboutId'
      fullPath: '/about/$aboutId'
      preLoaderRoute: typeof AboutAboutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRoute,
  AboutAboutIdRoute: AboutAboutIdRoute,
  AboutIndexRoute: AboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
